FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=utf-8 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    DEVELOPMENT=1

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        libldap2-dev \
        libsasl2-dev \
        libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /backend

# Create virtual environment
RUN python -m venv venv
RUN venv/bin/pip install --upgrade pip

# Install dependencies
COPY . .
RUN venv/bin/pip install -r requirements.txt

# Make scripts executable
COPY init.sh dev-entrypoint.sh ./
RUN chmod +x init.sh dev-entrypoint.sh

EXPOSE 8000
ENTRYPOINT ["./dev-entrypoint.sh"]