const members = [
  {
    id: "akshay.chanda@students.iiit.ac.in",
    name: "Akshay Chanda",
    email: "akshay.chanda@students.iiit.ac.in",
    rollNumber: "2024102014",
    year: "4th Year",
    department: "CSE",
    photoUrl: "/favicon.ico",
    phone: "+91 98765 43210",
    linkedin: "https://linkedin.com/in/akshaychanda",
    github: "https://github.com/akshaychanda",
    bio: "Passionate about building communities and fostering innovation.",
    achievements: [
      "Led team to win National Hackathon 2024",
      "Published research paper on AI/ML",
      "Organized 10+ technical workshops",
    ],
    interests: ["Machine Learning", "Web Development", "Community Building"],
    isAdmin: true,
    workHistory: [
      { role: "President", team: "NSS Core", start: "2024-06", end: null },
      { role: "Vice President", team: "NSS Core", start: "2023-06", end: "2024-05" },
      { role: "Technical Lead", team: "TECH", start: "2022-08", end: "2023-05" },
      { role: "Member", team: "TECH", start: "2022-01", end: "2022-07" },
    ],
  },
  {
    id: "sangameshwar.sale@students.iiit.ac.in",
    name: "Sangameshwar Sale",
    email: "sangameshwar.sale@students.iiit.ac.in",
    rollNumber: "2024102015",
    year: "3rd Year",
    department: "ECE",
    photoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTF5-3YjBcXTqKUlOAeUUtuOLKgQSma2wGG1g&s",
    phone: "+91 98765 43211",
    linkedin: "https://linkedin.com/in/sangameshwarsale",
    github: "https://github.com/sangameshwarsale",
    bio: "Tech enthusiast and problem solver. Currently serving as Vice President.",
    achievements: ["Winner of State-level Coding Competition", "Intern at leading tech company"],
    interests: ["Competitive Programming", "IoT", "Robotics"],
    isAdmin: true,
    workHistory: [
      { role: "Vice President", team: "NSS Core", start: "2024-06", end: null },
      { role: "Secretary", team: "NSS Core", start: "2023-06", end: "2024-05" },
      { role: "Member", team: "TECH", start: "2023-01", end: "2023-05" },
    ],
  },
  {
    id: "aditi.sharma@students.iiit.ac.in",
    name: "Aditi Sharma",
    email: "aditi.sharma@students.iiit.ac.in",
    rollNumber: "2024102016",
    year: "3rd Year",
    department: "CSE",
    photoUrl: "/favicon.ico",
    phone: "+91 98765 43212",
    linkedin: "https://linkedin.com/in/aditisharma",
    github: "https://github.com/aditisharma",
    bio: "Organizing events and managing teams is my forte. Currently serving as Secretary.",
    achievements: ["Coordinated 5+ major college events"],
    interests: ["Event Management", "Public Speaking"],
    isAdmin: true,
    workHistory: [
      { role: "Secretary", team: "NSS Core", start: "2024-01", end: null },
      { role: "Event Coordinator", team: "LOGISTICS", start: "2023-06", end: "2023-12" },
      { role: "Volunteer", team: "LOGISTICS", start: "2023-01", end: "2023-05" },
    ],
  },
  {
    id: "rahul.verma@students.iiit.ac.in",
    name: "Rahul Verma",
    email: "rahul.verma@students.iiit.ac.in",
    rollNumber: "2024102017",
    year: "2nd Year",
    department: "CSE",
    photoUrl: "/favicon.ico",
    phone: "+91 98765 43213",
    linkedin: "https://linkedin.com/in/rahulverma",
    github: "https://github.com/rahulverma",
    bio: "Numbers and finance enthusiast. Currently serving as Treasurer.",
    achievements: ["Managed club budget efficiently"],
    interests: ["Finance", "Data Analysis"],
    isAdmin: true,
    workHistory: [
      { role: "Treasurer", team: "NSS Core", start: "2024-06", end: null },
      { role: "Member", team: "NSS Core", start: "2024-01", end: "2024-05" },
    ],
  },
  {
    id: "priya.singh@students.iiit.ac.in",
    name: "Priya Singh",
    email: "priya.singh@students.iiit.ac.in",
    rollNumber: "2024102018",
    year: "4th Year",
    department: "CSE",
    photoUrl: "/favicon.ico",
    phone: "+91 98765 43214",
    linkedin: "https://linkedin.com/in/priyasingh",
    github: "https://github.com/priyasingh",
    bio: "Full-stack developer with a passion for open source. Currently Technical Lead.",
    achievements: ["Contributed to 10+ open source projects", "Mentored 20+ students"],
    interests: ["Web Development", "Open Source", "Mentoring"],
    isAdmin: false,
    workHistory: [
      { role: "Technical Lead", team: "TECH", start: "2023-08", end: null },
      { role: "Senior Developer", team: "TECH", start: "2022-08", end: "2023-07" },
      { role: "Developer", team: "TECH", start: "2022-01", end: "2022-07" },
    ],
  },
  {
    id: "neha.patel@students.iiit.ac.in",
    name: "Neha Patel",
    email: "neha.patel@students.iiit.ac.in",
    rollNumber: "2024102019",
    year: "3rd Year",
    department: "CSE",
    photoUrl: "/favicon.ico",
    phone: "+91 98765 43215",
    linkedin: "https://linkedin.com/in/nehapatel",
    github: "https://github.com/nehapatel",
    bio: "Creating beautiful and functional designs. Currently Design Head.",
    achievements: ["Designed UI for 5+ club projects"],
    interests: ["UI/UX Design", "Graphic Design"],
    isAdmin: false,
    workHistory: [
      { role: "Design Head", team: "DESIGN", start: "2024-06", end: null },
      { role: "Designer", team: "DESIGN", start: "2023-08", end: "2024-05" },
      { role: "Member", team: "DESIGN", start: "2023-01", end: "2023-07" },
    ],
  },
  {
    id: "vikram.reddy@students.iiit.ac.in",
    name: "Vikram Reddy",
    email: "vikram.reddy@students.iiit.ac.in",
    rollNumber: "2024102020",
    year: "2nd Year",
    department: "ECE",
    photoUrl: "/favicon.ico",
    phone: "+91 98765 43216",
    linkedin: "https://linkedin.com/in/vikramreddy",
    github: "https://github.com/vikramreddy",
    bio: "Spreading the word about tech and innovation. Currently Marketing Head.",
    achievements: ["Increased club social media engagement by 200%"],
    interests: ["Marketing", "Social Media", "Content Creation"],
    isAdmin: false,
    workHistory: [
      { role: "Marketing Head", team: "CONTENT", start: "2024-08", end: null },
      { role: "Content Creator", team: "CONTENT", start: "2024-01", end: "2024-07" },
    ],
  },
  {
    id: "rithik.palla@students.iiit.ac.in",
    name: "Rithik Palla",
    email: "rithik.palla@students.iiit.ac.in",
    rollNumber: "2024102021",
    year: "2nd Year",
    department: "CSE",
    photoUrl: "/favicon.ico",
    phone: "+91 98765 43217",
    linkedin: "https://linkedin.com/in/rithikpalla",
    github: "https://github.com/rithikpalla",
    bio: "Making events memorable and impactful. Currently Event Coordinator.",
    achievements: ["Coordinated 8+ successful events"],
    interests: ["Event Planning", "Team Coordination"],
    isAdmin: true,
    workHistory: [
      { role: "TECH HEAD", team: "TECH", start: "2024-06", end: null },
      { role: "Volunteer", team: "LOGISTICS", start: "2024-01", end: "2024-05" },
    ],
  },
  {
    id: "ananya.reddy@alumni.iiit.ac.in",
    name: "Ananya Reddy",
    email: "ananya.reddy@alumni.iiit.ac.in",
    rollNumber: "2021102045",
    year: "Alumni",
    department: "CSE",
    photoUrl: "/favicon.ico",
    phone: "+91 98765 43220",
    linkedin: "https://linkedin.com/in/ananyareddy",
    github: "https://github.com/ananyareddy",
    bio: "Former President of NSS (2023-2024). Now working as a Software Engineer.",
    achievements: [
      "Increased club membership by 150%",
      "Organized first-ever State-level Tech Summit",
      "Established partnerships with 5+ tech companies",
    ],
    interests: ["Leadership", "Community Service", "Technology"],
    isAdmin: false,
    workHistory: [
      { role: "President", team: "NSS Core", start: "2023-06", end: "2024-05" },
      { role: "Vice President", team: "NSS Core", start: "2022-06", end: "2023-05" },
      { role: "Technical Lead", team: "TECH", start: "2021-08", end: "2022-05" },
      { role: "Member", team: "TECH", start: "2021-01", end: "2021-07" },
    ],
  },
  {
    id: "karthik.iyer@alumni.iiit.ac.in",
    name: "Karthik Iyer",
    email: "karthik.iyer@alumni.iiit.ac.in",
    rollNumber: "2020102033",
    year: "Alumni",
    department: "CSE",
    photoUrl: "/favicon.ico",
    phone: "+91 98765 43221",
    linkedin: "https://linkedin.com/in/karthikiyer",
    github: "https://github.com/karthikiyer",
    bio: "Former Design Head. Created the visual identity of NSS. Currently a UX Designer at a startup.",
    achievements: [
      "Redesigned club website and branding",
      "Won Best Design Award at Techfest 2022",
    ],
    interests: ["UI/UX Design", "Branding", "Animation"],
    isAdmin: false,
    workHistory: [
      { role: "Design Head", team: "DESIGN", start: "2022-01", end: "2023-05" },
      { role: "Designer", team: "DESIGN", start: "2021-01", end: "2021-12" },
      { role: "Member", team: "CONTENT", start: "2020-08", end: "2020-12" },
    ],
  }
];

export default members;